generation_batch_size: 64
num_generations: 8
learning_rate: 1.0e-6
max_completion_length: 64
output_dir: "/checkpoint/scientific-reasoning/gaetan/trl/logs"
feedback_template: '{feedback_raw}'
reprompt_template: "{prompt}{feedback}"
distillation_mode: "full_logits"
distillation_alpha: 0.0
include_environment_feedback: True
num_train_epochs: 100
report_to: "wandb"
run_name: "base"
project: "trl-feedback-distillation"
logging_steps: 1
teacher_model_kind: "base"
log_completions: True
log_completions_steps: 10
logging_first_step: True
eval_strategy: "steps"
eval_steps: 10
eval_on_start: False
eval_teacher: True
num_generations_eval: 1
ddp_find_unused_parameters: True
scale_rewards: true
